var Lister=[
"Table%20of%20Contents.html",
"Independent VS Dependent Variables.html",
"Choosing the x and y axis.html",
"Scatter Plots.html",
"Drawing Scatter Plots.html" ,
"Relationships in Scatter Plots.html",
"Correlation%20Coefficients.html",
"Finding the Correlation Coefficient.html",
"Finding Correlation Coefficient EXAMPLE.html",
"Now You Try! (Correlation Coefficient).html",
"Interpreting Correlation.html",
"Testing Correlation.html",
"Testing Correlation EXAMPLE.html",
"Now You Try! (Testing Correlations).html",
"Correlation VS Causation.html",
"Regression.html",
"Sum of Squares.html",
"Calculating the regression line.html",
"Calculating the Regression Line (EXAMPLE).html",
"Now You Try! (regression lines).html",
"Week 12 Vocabulary.html",
"Week 12 Formula Sheet.html",
"Correlation and Regression.xlsx"
]
